
名字: 建筑

在:
  pull_request:
推:
分支:
      - "**"
    paths-ignore:
      - ".github/workflows/**"
      - "**.md"
      - "version_map.json"
  workflow_dispatch:
  workflow_call:

工作:
建筑:
名字: 为${{matrix.arch}}
战略:
矩阵:
拱: ["arm64"]
      fail-fast: 虚假的
环境:
      FCL_KEYSTORE_PASSWORD: ${{ secrets.FCL_KEYSTORE_PASSWORD }}
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      OAUTH_API_KEY: ${{ secrets.OAUTH_API_KEY }}
    runs-on: ubuntu-latest
步骤:
      - 名字: 结账代码
用途: actions/checkout@v7
与:
          fetch-depth: 0
子模块: 递归的

      - 名字: 设置 JDK 17
用途: actions/setup-java@v5
与:
分布: "temurin"
          java-version: 17
贮存物: "gradle"

      - 名字: 构建发布 apk
如果: ${{github.repository_owner =='FCL-Team'&& github.event_name !='pull_request' }}
跑: |
将 gradlew you you:chmod+x gradlew
/gradlew assemblelelease-Darch=${{{matrix.arch}}}-no-守护进程

      - 名字: 构建调试 apk
如果: ${{github.repository_owner !='FCL-Team'|| github.event_name =='pull_request' }}
跑: |
将 gradlew you you:chmod+x gradlew
/gradlew assemblefordebug-Darch=${{{matrix.arch}}}-no-守护进程

      - 名字: 上载 apk
用途: actions/upload-artifact@v6
与:
名字: 应用-${{matrix.arch}}
路径: FCL/build/outputs/apk/*/*
        #保留天数：1
